# Generated by Django 3.0.2 on 2020-02-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoderestriction',
            name='type',
            field=models.CharField(choices=[('DATE', 'Fecha'), ('STOCK', 'Cantidad'), ('EMAIL', 'Email'), ('DOMAIN', 'Dominio')], max_length=10),
        ),
    ]
