# Generated by Django 3.0.2 on 2020-02-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_discount_code_restriction_add_domain_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount',
        ),
    ]
