# Generated by Django 3.0.3 on 2020-02-11 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_notes_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='fixed_value',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percentage',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
