# Generated by Django 3.0.3 on 2020-02-11 03:56

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_discount_code_remove_unnecesary_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='fixed_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso')], default='ARS', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='fixed_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ARS', max_digits=7, null=True),
        ),
    ]
