# Generated by Django 3.0.3 on 2020-02-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_discount_code_fixed_value_to_money_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='image/items/'),
        ),
    ]
