# Generated by Django 3.0.3 on 2020-02-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='file',
            field=models.FileField(upload_to='documents/credit_notes/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to='documents/invoices/'),
        ),
    ]
