# Generated by Django 3.0.3 on 2020-02-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_direct_relationship_with_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemoption',
            unique_together={('order_item', 'item_option')},
        ),
    ]
