# Generated by Django 3.0.3 on 2020-02-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_external_ids_and_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='cancellation',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
