# Generated by Django 3.0.3 on 2020-02-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_payment_refund_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identity_document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PSP', 'Pasaporte')], default='DNI', max_length=3),
            preserve_default=False,
        ),
    ]
