# Generated by Django 3.0.3 on 2020-02-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_customer_identity_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='identity_document_type',
        ),
    ]
