# Generated by Django 3.0.3 on 2020-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_remove_customer_identity_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cae',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
